/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import packagee.app.ApplicationContext;
import packagee.app.Main;
import packagee.controller.AuthController;
import packagee.controller.DoctorController;
import packagee.controller.PatientController;
import packagee.controller.TableController;
import packagee.dto.DoctorDTO;
import packagee.dto.PatientDTO;
import packagee.model.*;
import packagee.observer.ModelEvent;
import packagee.observer.ModelEventType;
import packagee.observer.ModelObserver;
import packagee.model.enums.*;
import packagee.request.DoctorRequest;
import packagee.response.Response;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class AdminView extends javax.swing.JFrame implements ModelObserver {

    private int x, y;
    private ArrayList<User> users;
    private ArrayList<Appointment>appointments;
    private ArrayList<Hospitalization>hospitalizations;
    private User user;
    private ApplicationContext applicationContext;
    private AuthController authController;
    private DoctorController doctorController;
    private PatientController patientController;
    private TableController tableController;

    public AdminView(ApplicationContext applicationContext, User user) {
        initComponents();
        this.applicationContext = applicationContext;
        this.authController = applicationContext.getAuthController();
        this.doctorController = applicationContext.getDoctorController();
        this.patientController = applicationContext.getPatientController();
        this.tableController = applicationContext.getTableController();
        this.user = user;
        loadLegacyCollectionsFromContext();
        initializeAdminView();
        this.applicationContext.getModelEventPublisher().addObserver(this);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

   
    public AdminView(User user, ArrayList<User>users,ArrayList<Hospitalization> hospitalizations, ArrayList<Appointment> appointments) {
        this(resolveApplicationContext(), user);
    }

    private static ApplicationContext resolveApplicationContext() {
        ApplicationContext context = Main.getApplicationContext();
        if (context == null) {
            context = new ApplicationContext();
            context.initialize();
        }
        return context;
    }

    @SuppressWarnings("unchecked")
    private void loadLegacyCollectionsFromContext() {
        this.users = (ArrayList<User>) applicationContext.getDataStore().getUsers();
        this.hospitalizations = (ArrayList<Hospitalization>) applicationContext.getDataStore().getHospitalizations();
        this.appointments = (ArrayList<Appointment>) applicationContext.getDataStore().getAppointments();
    }

    private void initializeAdminView() {
        loadDoctorComboBox();
        loadPatientComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlAdminWindow = new packagee.PanelRound();
        pnlAdminHeader = new packagee.PanelRound();
        btnCloseAdmin = new javax.swing.JButton();
        lblAdminTitle = new javax.swing.JLabel();
        pnlDoctorRegistration = new packagee.PanelRound();
        btnOpenDoctorView = new javax.swing.JButton();
        btnOpenPatientView = new javax.swing.JButton();
        lblDoctorFirstName = new javax.swing.JLabel();
        txtDoctorFirstName = new javax.swing.JTextField();
        lblDoctorLastName = new javax.swing.JLabel();
        txtDoctorLastName = new javax.swing.JTextField();
        lblDoctorId = new javax.swing.JLabel();
        txtDoctorId = new javax.swing.JTextField();
        lblDoctorSpecialty = new javax.swing.JLabel();
        lblDoctorLicenseNumber = new javax.swing.JLabel();
        txtDoctorLicenseNumber = new javax.swing.JTextField();
        lblDoctorAssignedOffice = new javax.swing.JLabel();
        txtDoctorAssignedOffice = new javax.swing.JTextField();
        lblDoctorUsername = new javax.swing.JLabel();
        txtDoctorUsername = new javax.swing.JTextField();
        lblDoctorPassword = new javax.swing.JLabel();
        txtDoctorPassword = new javax.swing.JTextField();
        lblDoctorConfirmPassword = new javax.swing.JLabel();
        txtDoctorConfirmPassword = new javax.swing.JTextField();
        cmbDoctorSpecialty = new javax.swing.JComboBox<>();
        btnRegisterDoctor = new javax.swing.JButton();
        sepDoctorFormActions = new javax.swing.JSeparator();
        cmbAdminDoctors = new javax.swing.JComboBox<>();
        lblAdminDoctorSelector = new javax.swing.JLabel();
        lblAdminPatientSelector = new javax.swing.JLabel();
        cmbAdminPatients = new javax.swing.JComboBox<>();
        sepAdminNavigation = new javax.swing.JSeparator();
        btnLogoutAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlAdminWindow.setRadius(50);

        pnlAdminHeader.setRadius(50);
        pnlAdminHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        pnlAdminHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        btnCloseAdmin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCloseAdmin.setText("X");
        btnCloseAdmin.setBorderPainted(false);
        btnCloseAdmin.setContentAreaFilled(false);
        btnCloseAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCloseAdmin.setFocusable(false);
        btnCloseAdmin.setRequestFocusEnabled(false);
        btnCloseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseAdminActionPerformed(evt);
            }
        });

        lblAdminTitle.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblAdminTitle.setText("ADMIN VIEW");

        javax.swing.GroupLayout pnlAdminHeaderLayout = new javax.swing.GroupLayout(pnlAdminHeader);
        pnlAdminHeader.setLayout(pnlAdminHeaderLayout);
        pnlAdminHeaderLayout.setHorizontalGroup(
            pnlAdminHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminHeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAdminTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseAdmin)
                .addGap(19, 19, 19))
        );
        pnlAdminHeaderLayout.setVerticalGroup(
            pnlAdminHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnCloseAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAdminTitle))
        );

        btnOpenDoctorView.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnOpenDoctorView.setText("DOCTOR VIEW");
        btnOpenDoctorView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDoctorViewActionPerformed(evt);
            }
        });

        btnOpenPatientView.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnOpenPatientView.setText("PATIENT VIEW");
        btnOpenPatientView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenPatientViewActionPerformed(evt);
            }
        });

        lblDoctorFirstName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDoctorFirstName.setText("Firstname");

        txtDoctorFirstName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDoctorLastName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDoctorLastName.setText("Lastname");

        txtDoctorLastName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDoctorId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDoctorId.setText("ID");

        txtDoctorId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDoctorSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDoctorSpecialty.setText("Specialty");

        lblDoctorLicenseNumber.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDoctorLicenseNumber.setText("License Number");

        txtDoctorLicenseNumber.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDoctorAssignedOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDoctorAssignedOffice.setText("Assigned office");

        txtDoctorAssignedOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDoctorUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDoctorUsername.setText("User");

        txtDoctorUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDoctorPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDoctorPassword.setText("Password");

        txtDoctorPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDoctorConfirmPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDoctorConfirmPassword.setText("Password confirmation");

        txtDoctorConfirmPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        cmbDoctorSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbDoctorSpecialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        btnRegisterDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRegisterDoctor.setText("Save");
        btnRegisterDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterDoctorActionPerformed(evt);
            }
        });

        sepDoctorFormActions.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cmbAdminDoctors.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbAdminDoctors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        lblAdminDoctorSelector.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAdminDoctorSelector.setText("Doctor");

        lblAdminPatientSelector.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAdminPatientSelector.setText("Patient");

        cmbAdminPatients.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbAdminPatients.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        sepAdminNavigation.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnLogoutAdmin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogoutAdmin.setText("Logout");
        btnLogoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDoctorRegistrationLayout = new javax.swing.GroupLayout(pnlDoctorRegistration);
        pnlDoctorRegistration.setLayout(pnlDoctorRegistrationLayout);
        pnlDoctorRegistrationLayout.setHorizontalGroup(
            pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btnRegisterDoctor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                                .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDoctorFirstName)
                                    .addComponent(lblDoctorSpecialty))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                                        .addComponent(cmbDoctorSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDoctorLicenseNumber)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDoctorLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                                        .addComponent(txtDoctorFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(lblDoctorLastName)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDoctorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDoctorId)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDoctorId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                                .addComponent(lblDoctorAssignedOffice)
                                .addGap(18, 18, 18)
                                .addComponent(txtDoctorAssignedOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                                    .addComponent(lblDoctorUsername)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDoctorUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                                    .addComponent(lblDoctorPassword)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDoctorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                                    .addComponent(lblDoctorConfirmPassword)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDoctorConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOpenDoctorView)
                            .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cmbAdminDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lblAdminDoctorSelector)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDoctorRegistrationLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogoutAdmin)
                        .addGap(318, 318, 318)))
                .addComponent(sepDoctorFormActions, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOpenPatientView)
                            .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(cmbAdminPatients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblAdminPatientSelector)))
                .addGap(88, 88, 88))
            .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDoctorRegistrationLayout.createSequentialGroup()
                    .addContainerGap(707, Short.MAX_VALUE)
                    .addComponent(sepAdminNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(523, 523, 523)))
        );
        pnlDoctorRegistrationLayout.setVerticalGroup(
            pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                .addComponent(sepDoctorFormActions)
                .addContainerGap())
            .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorFirstName)
                    .addComponent(txtDoctorFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDoctorLastName)
                    .addComponent(txtDoctorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDoctorId)
                    .addComponent(txtDoctorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorSpecialty)
                    .addComponent(cmbDoctorSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDoctorLicenseNumber)
                    .addComponent(txtDoctorLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDoctorAssignedOffice)
                    .addComponent(txtDoctorAssignedOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDoctorUsername)
                            .addComponent(txtDoctorUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDoctorPassword)
                            .addComponent(txtDoctorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDoctorConfirmPassword)
                            .addComponent(txtDoctorConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblAdminDoctorSelector)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAdminDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnOpenDoctorView)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnRegisterDoctor)
                .addGap(123, 123, 123)
                .addComponent(btnLogoutAdmin)
                .addGap(38, 38, 38))
            .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(lblAdminPatientSelector)
                .addGap(18, 18, 18)
                .addComponent(cmbAdminPatients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnOpenPatientView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlDoctorRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlDoctorRegistrationLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sepAdminNavigation)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout pnlAdminWindowLayout = new javax.swing.GroupLayout(pnlAdminWindow);
        pnlAdminWindow.setLayout(pnlAdminWindowLayout);
        pnlAdminWindowLayout.setHorizontalGroup(
            pnlAdminWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdminHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDoctorRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAdminWindowLayout.setVerticalGroup(
            pnlAdminWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminWindowLayout.createSequentialGroup()
                .addComponent(pnlAdminHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDoctorRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdminWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdminWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {                                         
        x = evt.getX();
        y = evt.getY();
    }                                        

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {                                         
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }                                        

    private void btnCloseAdminActionPerformed(java.awt.event.ActionEvent evt) {                                              
        System.exit(0);
    }                                             

    private void btnRegisterDoctorActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        DoctorRequest request = new DoctorRequest(
                txtDoctorId.getText().trim(),
                txtDoctorUsername.getText().trim(),
                txtDoctorFirstName.getText().trim(),
                txtDoctorLastName.getText().trim(),
                txtDoctorPassword.getText(),
                txtDoctorConfirmPassword.getText(),
                normalizeSpecialty(selectedComboValue(cmbDoctorSpecialty)),
                txtDoctorLicenseNumber.getText().trim(),
                txtDoctorAssignedOffice.getText().trim()
        );

        Response<?> response = doctorController.registerDoctor(request);
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isSuccess()) {
            clearDoctorRegistrationFields();
            loadLegacyCollectionsFromContext();
            loadDoctorComboBox();
        }
    }                                                 

    private void btnOpenDoctorViewActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        String idDoctor = selectedComboValue(cmbAdminDoctors);
        Response<DoctorDTO> response = doctorController.getDoctorInfo(idDoctor);
        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(this, response.getMessage());
            return;
        }
        Doctor doctorModel = applicationContext.getUserRepository()
                .findDoctorById(Long.parseLong(idDoctor.trim()))
                .orElse(null);
        DoctorView doctor = new DoctorView(applicationContext, user, doctorModel);
        this.dispose();
        doctor.setVisible(true);
    }                                                 

    private void btnLogoutAdminActionPerformed(java.awt.event.ActionEvent evt) {                                               
        authController.logout();
        LoginView login = new LoginView(applicationContext);
        this.dispose();
        login.setVisible(true);
    }                                              

    private void btnOpenPatientViewActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        String idPatient = selectedComboValue(cmbAdminPatients);
        Response<PatientDTO> response = patientController.getPatientInfo(idPatient);
        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(this, response.getMessage());
            return;
        }
        Patient patientModel = applicationContext.getUserRepository()
                .findPatientById(Long.parseLong(idPatient.trim()))
                .orElse(null);
        PatientView patient = new PatientView(applicationContext, user, patientModel);
        this.dispose();
        patient.setVisible(true);
    }                                                  


    private void loadDoctorComboBox() {
        cmbAdminDoctors.removeAllItems();
        cmbAdminDoctors.addItem("Select one");
        Response<java.util.List<DoctorDTO>> response = doctorController.getAllDoctors();
        if (response.isSuccess()) {
            for (DoctorDTO doctor : response.getData()) {
                cmbAdminDoctors.addItem(String.valueOf(doctor.getId()));
            }
        }
    }

    private void loadPatientComboBox() {
        cmbAdminPatients.removeAllItems();
        cmbAdminPatients.addItem("Select one");
        Response<java.util.List<PatientDTO>> response = patientController.getAllPatients();
        if (response.isSuccess()) {
            for (PatientDTO patient : response.getData()) {
                cmbAdminPatients.addItem(String.valueOf(patient.getId()));
            }
        }
    }

    private String selectedComboValue(javax.swing.JComboBox<String> comboBox) {
        Object selected = comboBox.getSelectedItem();
        if (selected == null || "Select one".equalsIgnoreCase(selected.toString())) {
            return "";
        }
        return selected.toString();
    }


    @Override
    public void onModelChanged(ModelEvent event) {
        if (event == null || applicationContext == null) {
            return;
        }
        SwingUtilities.invokeLater(() -> {
            if (event.getType() == ModelEventType.USERS_CHANGED || event.getType() == ModelEventType.ALL_CHANGED) {
                loadDoctorComboBox();
                loadPatientComboBox();
            }
        });
    }

    @Override
    public void dispose() {
        if (applicationContext != null) {
            applicationContext.getModelEventPublisher().removeObserver(this);
        }
        super.dispose();
    }

    private Long selectedLongFromCombo(javax.swing.JComboBox<String> comboBox, String errorMessage) {
        String selected = selectedComboValue(comboBox);
        try {
            return Long.parseLong(selected);
        } catch (NumberFormatException ex) {
            return null;
        }
    }

    private String normalizeSpecialty(String value) {
        if (value == null || value.trim().isEmpty()) {
            return "";
        }
        return value.trim().toUpperCase().replace(" & ", "_").replace(" ", "_");
    }

    private void clearDoctorRegistrationFields() {
        txtDoctorFirstName.setText("");
        txtDoctorLastName.setText("");
        txtDoctorId.setText("");
        txtDoctorLicenseNumber.setText("");
        txtDoctorAssignedOffice.setText("");
        txtDoctorUsername.setText("");
        txtDoctorPassword.setText("");
        txtDoctorConfirmPassword.setText("");
        cmbDoctorSpecialty.setSelectedIndex(0);
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCloseAdmin;
    private javax.swing.JButton btnLogoutAdmin;
    private javax.swing.JButton btnOpenDoctorView;
    private javax.swing.JButton btnOpenPatientView;
    private javax.swing.JButton btnRegisterDoctor;
    private javax.swing.JComboBox<String> cmbDoctorSpecialty;
    private javax.swing.JComboBox<String> cmbAdminDoctors;
    private javax.swing.JComboBox<String> cmbAdminPatients;
    private javax.swing.JLabel lblAdminTitle;
    private javax.swing.JLabel lblDoctorUsername;
    private javax.swing.JLabel lblDoctorPassword;
    private javax.swing.JLabel lblDoctorConfirmPassword;
    private javax.swing.JLabel lblAdminDoctorSelector;
    private javax.swing.JLabel lblAdminPatientSelector;
    private javax.swing.JLabel lblDoctorFirstName;
    private javax.swing.JLabel lblDoctorLastName;
    private javax.swing.JLabel lblDoctorId;
    private javax.swing.JLabel lblDoctorSpecialty;
    private javax.swing.JLabel lblDoctorLicenseNumber;
    private javax.swing.JLabel lblDoctorAssignedOffice;
    private javax.swing.JSeparator sepDoctorFormActions;
    private javax.swing.JSeparator sepAdminNavigation;
    private javax.swing.JTextField txtDoctorConfirmPassword;
    private javax.swing.JTextField txtDoctorFirstName;
    private javax.swing.JTextField txtDoctorLastName;
    private javax.swing.JTextField txtDoctorId;
    private javax.swing.JTextField txtDoctorLicenseNumber;
    private javax.swing.JTextField txtDoctorAssignedOffice;
    private javax.swing.JTextField txtDoctorUsername;
    private javax.swing.JTextField txtDoctorPassword;
    private packagee.PanelRound pnlAdminWindow;
    private packagee.PanelRound pnlAdminHeader;
    private packagee.PanelRound pnlDoctorRegistration;
    // End of variables declaration                   
}
