/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import packagee.app.ApplicationContext;
import packagee.app.Main;
import packagee.controller.AuthController;
import packagee.dto.UserDTO;
import packagee.model.Administrator;
import packagee.model.Appointment;
import packagee.model.Doctor;
import packagee.model.Hospitalization;
import packagee.model.Patient;
import packagee.model.User;
import packagee.request.LoginRequest;
import packagee.request.PatientRequest;
import packagee.response.Response;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class LoginView extends javax.swing.JFrame {

    private int x, y;
    private ApplicationContext applicationContext;
    private AuthController authController;
    private packagee.controller.PatientController patientController;
    private ArrayList<User> users;
    private ArrayList<Hospitalization> hospitalizations;
    private ArrayList<Appointment> appointments;

    /**
     * Constructor por defecto conservado para compatibilidad con NetBeans.
     * Resuelve el contexto creado en Main y, si no existe, crea uno temporal.
     */
    public LoginView() {
        this(resolveApplicationContext());
    }

    /**
     * Constructor usado por Main.
     * La vista recibe los controladores ya creados en ApplicationContext.
     */
    public LoginView(ApplicationContext applicationContext) {
        initComponents();
        this.applicationContext = applicationContext;
        this.authController = applicationContext.getAuthController();
        this.patientController = applicationContext.getPatientController();
        loadLegacyCollectionsFromContext();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    private static ApplicationContext resolveApplicationContext() {
        ApplicationContext context = Main.getApplicationContext();
        if (context == null) {
            context = new ApplicationContext();
            context.initialize();
        }
        return context;
    }

    @SuppressWarnings("unchecked")
    private void loadLegacyCollectionsFromContext() {
        this.users = (ArrayList<User>) applicationContext.getDataStore().getUsers();
        this.hospitalizations = (ArrayList<Hospitalization>) applicationContext.getDataStore().getHospitalizations();
        this.appointments = (ArrayList<Appointment>) applicationContext.getDataStore().getAppointments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLoginWindow = new packagee.PanelRound();
        pnlLoginHeader = new packagee.PanelRound();
        btnCloseLogin = new javax.swing.JButton();
        tabLoginAndRegistration = new javax.swing.JTabbedPane();
        pnlLoginContent = new packagee.PanelRound();
        lblLoginTitle = new javax.swing.JLabel();
        txtLoginUsername = new javax.swing.JTextField();
        lblLoginUsername = new javax.swing.JLabel();
        txtLoginPassword = new javax.swing.JTextField();
        lblLoginPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        pnlPatientRegistration = new javax.swing.JPanel();
        lblPatientFirstName = new javax.swing.JLabel();
        txtPatientFirstName = new javax.swing.JTextField();
        lblPatientLastName = new javax.swing.JLabel();
        txtPatientLastName = new javax.swing.JTextField();
        lblPatientId = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        lblPatientGender = new javax.swing.JLabel();
        lblPatientPhone = new javax.swing.JLabel();
        txtPatientPhone = new javax.swing.JTextField();
        lblPatientEmail = new javax.swing.JLabel();
        txtPatientEmail = new javax.swing.JTextField();
        lblPatientUsername = new javax.swing.JLabel();
        txtPatientUsername = new javax.swing.JTextField();
        txtPatientPassword = new javax.swing.JTextField();
        lblPatientPassword = new javax.swing.JLabel();
        lblPatientConfirmPassword = new javax.swing.JLabel();
        txtPatientConfirmPassword = new javax.swing.JTextField();
        cmbPatientGender = new javax.swing.JComboBox<>();
        btnRegisterPatient = new javax.swing.JButton();
        lblPatientAddress = new javax.swing.JLabel();
        txtPatientAddress = new javax.swing.JTextField();
        lblPatientBirthdate = new javax.swing.JLabel();
        txtPatientBirthdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlLoginWindow.setRadius(50);

        pnlLoginHeader.setRadius(50);
        pnlLoginHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        pnlLoginHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        btnCloseLogin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCloseLogin.setText("X");
        btnCloseLogin.setBorderPainted(false);
        btnCloseLogin.setContentAreaFilled(false);
        btnCloseLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCloseLogin.setFocusable(false);
        btnCloseLogin.setRequestFocusEnabled(false);
        btnCloseLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginHeaderLayout = new javax.swing.GroupLayout(pnlLoginHeader);
        pnlLoginHeader.setLayout(pnlLoginHeaderLayout);
        pnlLoginHeaderLayout.setHorizontalGroup(
            pnlLoginHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseLogin)
                .addGap(19, 19, 19))
        );
        pnlLoginHeaderLayout.setVerticalGroup(
            pnlLoginHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCloseLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblLoginTitle.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblLoginTitle.setText("LOGIN");

        txtLoginUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLoginUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblLoginUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLoginUsername.setText("USERNAME");

        txtLoginPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLoginPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblLoginPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLoginPassword.setText("PASSWORD");

        btnLogin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogin.setText("ENTER");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginContentLayout = new javax.swing.GroupLayout(pnlLoginContent);
        pnlLoginContent.setLayout(pnlLoginContentLayout);
        pnlLoginContentLayout.setHorizontalGroup(
            pnlLoginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginContentLayout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(lblLoginTitle)
                .addGap(481, 481, 481))
            .addGroup(pnlLoginContentLayout.createSequentialGroup()
                .addGroup(pnlLoginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginContentLayout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(pnlLoginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginContentLayout.createSequentialGroup()
                                .addGroup(pnlLoginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLoginPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLoginUsername, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlLoginContentLayout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(btnLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLoginContentLayout.setVerticalGroup(
            pnlLoginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginContentLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblLoginTitle)
                .addGap(74, 74, 74)
                .addComponent(lblLoginUsername)
                .addGap(18, 18, 18)
                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLoginPassword)
                .addGap(18, 18, 18)
                .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnLogin)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        tabLoginAndRegistration.addTab("Login", pnlLoginContent);

        lblPatientFirstName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientFirstName.setText("Firstname");

        txtPatientFirstName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientLastName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientLastName.setText("Lastname");

        txtPatientLastName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientId.setText("ID");

        txtPatientId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientGender.setText("Gender");

        lblPatientPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientPhone.setText("Phone");

        txtPatientPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientEmail.setText("Email");

        txtPatientEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientUsername.setText("User");

        txtPatientUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPatientPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientPassword.setText("Password");

        lblPatientConfirmPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientConfirmPassword.setText("Password confirmation");

        txtPatientConfirmPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPatientConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientConfirmPasswordActionPerformed(evt);
            }
        });

        cmbPatientGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbPatientGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        btnRegisterPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRegisterPatient.setText("Save");
        btnRegisterPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPatientActionPerformed(evt);
            }
        });

        lblPatientAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientAddress.setText("Address");

        txtPatientAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientBirthdate.setText("Birthdate");

        txtPatientBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlPatientRegistrationLayout = new javax.swing.GroupLayout(pnlPatientRegistration);
        pnlPatientRegistration.setLayout(pnlPatientRegistrationLayout);
        pnlPatientRegistrationLayout.setHorizontalGroup(
            pnlPatientRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientRegistrationLayout.createSequentialGroup()
                .addGroup(pnlPatientRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPatientRegistrationLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(lblPatientPassword))
                    .addGroup(pnlPatientRegistrationLayout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(pnlPatientRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPatientUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPatientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPatientRegistrationLayout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(lblPatientUsername))
                    .addGroup(pnlPatientRegistrationLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(txtPatientConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPatientRegistrationLayout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(btnRegisterPatient))
                    .addGroup(pnlPatientRegistrationLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(lblPatientConfirmPassword))
                    .addGroup(pnlPatientRegistrationLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(pnlPatientRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlPatientRegistrationLayout.createSequentialGroup()
                                .addComponent(lblPatientBirthdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPatientBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPatientRegistrationLayout.createSequentialGroup()
                                .addComponent(lblPatientFirstName)
                                .addGap(34, 34, 34)
                                .addComponent(txtPatientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPatientRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatientLastName)
                            .addComponent(lblPatientAddress))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPatientRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlPatientRegistrationLayout.createSequentialGroup()
                                .addComponent(txtPatientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPatientId)
                                .addGap(30, 30, 30)
                                .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPatientGender)
                                .addGap(26, 26, 26)
                                .addComponent(cmbPatientGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPatientRegistrationLayout.createSequentialGroup()
                                .addComponent(txtPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPatientPhone)
                                .addGap(18, 18, 18)
                                .addComponent(txtPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPatientEmail)
                                .addGap(18, 18, 18)
                                .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        pnlPatientRegistrationLayout.setVerticalGroup(
            pnlPatientRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientRegistrationLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlPatientRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientFirstName)
                    .addComponent(txtPatientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientLastName)
                    .addComponent(txtPatientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientId)
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientGender)
                    .addComponent(cmbPatientGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPatientRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPatientRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPatientBirthdate)
                        .addComponent(txtPatientBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPatientAddress)
                        .addComponent(txtPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPatientPhone)
                        .addComponent(txtPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPatientRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPatientEmail)
                        .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(lblPatientUsername)
                .addGap(18, 18, 18)
                .addComponent(txtPatientUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPatientPassword)
                .addGap(18, 18, 18)
                .addComponent(txtPatientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPatientConfirmPassword)
                .addGap(18, 18, 18)
                .addComponent(txtPatientConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnRegisterPatient)
                .addGap(42, 42, 42))
        );

        tabLoginAndRegistration.addTab("Patient register", pnlPatientRegistration);

        javax.swing.GroupLayout pnlLoginWindowLayout = new javax.swing.GroupLayout(pnlLoginWindow);
        pnlLoginWindow.setLayout(pnlLoginWindowLayout);
        pnlLoginWindowLayout.setHorizontalGroup(
            pnlLoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoginHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLoginWindowLayout.createSequentialGroup()
                .addComponent(tabLoginAndRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlLoginWindowLayout.setVerticalGroup(
            pnlLoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginWindowLayout.createSequentialGroup()
                .addComponent(pnlLoginHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabLoginAndRegistration)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoginWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoginWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void btnCloseLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseLoginActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseLoginActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtLoginUsername.getText().trim();
        String password = txtLoginPassword.getText();

        LoginRequest request = new LoginRequest(username, password);
        Response<UserDTO> response = authController.login(request);

        JOptionPane.showMessageDialog(this, response.getMessage());

        if (!response.isSuccess()) {
            txtLoginPassword.setText("");
            return;
        }

        clearLoginFields();
        openViewByLoggedUser(response.getData());

    }//GEN-LAST:event_btnLoginActionPerformed

    private void clearLoginFields() {
        txtLoginUsername.setText("");
        txtLoginPassword.setText("");
    }

    private void openViewByLoggedUser(UserDTO loggedUser) {
        if (loggedUser == null) {
            JOptionPane.showMessageDialog(this, "No fue posible obtener la informacion del usuario autenticado.");
            return;
        }

        User selectedUser = applicationContext.getUserRepository()
                .findById(loggedUser.getId())
                .orElse(null);

        if (selectedUser == null) {
            JOptionPane.showMessageDialog(this, "El usuario autenticado no existe en el almacenamiento.");
            return;
        }

        if (selectedUser instanceof Administrator) {
            AdminView adminView = new AdminView(applicationContext, selectedUser);
            this.setVisible(false);
            adminView.setVisible(true);
            return;
        }

        if (selectedUser instanceof Doctor) {
            Doctor doctor = (Doctor) selectedUser;
            DoctorView doctorView = new DoctorView(applicationContext, selectedUser, doctor);
            this.setVisible(false);
            doctorView.setVisible(true);
            return;
        }

        if (selectedUser instanceof Patient) {
            Patient patient = (Patient) selectedUser;
            PatientView patientView = new PatientView(applicationContext, selectedUser, patient);
            this.setVisible(false);
            patientView.setVisible(true);
            return;
        }

        JOptionPane.showMessageDialog(this, "Tipo de usuario no reconocido.");
    }

    private void btnRegisterPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPatientActionPerformed
        PatientRequest request = new PatientRequest(
                txtPatientId.getText().trim(),
                txtPatientUsername.getText().trim(),
                txtPatientFirstName.getText().trim(),
                txtPatientLastName.getText().trim(),
                txtPatientPassword.getText(),
                txtPatientConfirmPassword.getText(),
                txtPatientEmail.getText().trim(),
                txtPatientBirthdate.getText().trim(),
                selectedComboValue(cmbPatientGender),
                txtPatientPhone.getText().trim(),
                txtPatientAddress.getText().trim()
        );

        Response<?> response = patientController.registerPatient(request);
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isSuccess()) {
            clearPatientRegistrationFields();
            loadLegacyCollectionsFromContext();
        }
    }//GEN-LAST:event_btnRegisterPatientActionPerformed


    private String selectedComboValue(javax.swing.JComboBox<String> comboBox) {
        Object selected = comboBox.getSelectedItem();
        if (selected == null || "Select one".equalsIgnoreCase(selected.toString())) {
            return "";
        }
        return selected.toString();
    }

    private void clearPatientRegistrationFields() {
        txtPatientFirstName.setText("");
        txtPatientLastName.setText("");
        txtPatientId.setText("");
        txtPatientPhone.setText("");
        txtPatientEmail.setText("");
        txtPatientUsername.setText("");
        txtPatientPassword.setText("");
        txtPatientConfirmPassword.setText("");
        txtPatientAddress.setText("");
        txtPatientBirthdate.setText("");
        cmbPatientGender.setSelectedIndex(0);
    }

    private void txtPatientConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientConfirmPasswordActionPerformed

    /**
     * La vista no se ejecuta a si misma.
     * El punto de entrada oficial del proyecto es packagee.app.Main.
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseLogin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegisterPatient;
    private javax.swing.JComboBox<String> cmbPatientGender;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblPatientUsername;
    private javax.swing.JLabel lblPatientPassword;
    private javax.swing.JLabel lblPatientConfirmPassword;
    private javax.swing.JLabel lblPatientAddress;
    private javax.swing.JLabel lblPatientBirthdate;
    private javax.swing.JLabel lblLoginUsername;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblPatientFirstName;
    private javax.swing.JLabel lblPatientLastName;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPatientGender;
    private javax.swing.JLabel lblPatientPhone;
    private javax.swing.JLabel lblPatientEmail;
    private javax.swing.JPanel pnlPatientRegistration;
    private javax.swing.JTabbedPane tabLoginAndRegistration;
    private javax.swing.JTextField txtLoginUsername;
    private javax.swing.JTextField txtPatientConfirmPassword;
    private javax.swing.JTextField txtPatientAddress;
    private javax.swing.JTextField txtPatientBirthdate;
    private javax.swing.JTextField txtLoginPassword;
    private javax.swing.JTextField txtPatientFirstName;
    private javax.swing.JTextField txtPatientLastName;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPatientPhone;
    private javax.swing.JTextField txtPatientEmail;
    private javax.swing.JTextField txtPatientUsername;
    private javax.swing.JTextField txtPatientPassword;
    private packagee.PanelRound pnlLoginWindow;
    private packagee.PanelRound pnlLoginHeader;
    private packagee.PanelRound pnlLoginContent;
    // End of variables declaration//GEN-END:variables
}
