/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import packagee.app.ApplicationContext;
import packagee.app.Main;
import packagee.controller.AppointmentController;
import packagee.controller.AuthController;
import packagee.controller.DoctorController;
import packagee.controller.HospitalizationController;
import packagee.controller.PatientController;
import packagee.controller.TableController;
import packagee.dto.AppointmentDTO;
import packagee.dto.DoctorDTO;
import packagee.model.*;
import packagee.observer.ModelEvent;
import packagee.observer.ModelEventType;
import packagee.observer.ModelObserver;
import packagee.model.enums.*;
import packagee.request.AppointmentRequest;
import packagee.request.HospitalizationRequest;
import packagee.request.PatientRequest;
import packagee.response.Response;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class PatientView extends javax.swing.JFrame implements ModelObserver {

    private int x, y;
    private User user;
    private ArrayList<User> users;
    private Patient patient;
    private ArrayList<Appointment> appointments;
    private ArrayList<Hospitalization> hospitalizations;
    private ApplicationContext applicationContext;
    private AuthController authController;
    private PatientController patientController;
    private DoctorController doctorController;
    private AppointmentController appointmentController;
    private HospitalizationController hospitalizationController;
    private TableController tableController;

    public PatientView(ApplicationContext applicationContext, User user, Patient patient) {
        initComponents();
        this.applicationContext = applicationContext;
        this.authController = applicationContext.getAuthController();
        this.patientController = applicationContext.getPatientController();
        this.doctorController = applicationContext.getDoctorController();
        this.appointmentController = applicationContext.getAppointmentController();
        this.hospitalizationController = applicationContext.getHospitalizationController();
        this.tableController = applicationContext.getTableController();
        this.user = user;
        this.patient = patient;
        loadLegacyCollectionsFromContext();
        initializePatientView();
        this.applicationContext.getModelEventPublisher().addObserver(this);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * Constructor anterior conservado para compatibilidad con llamadas existentes.
     */
    public PatientView(User user,Patient patient, ArrayList<User> users, ArrayList<Appointment>appointments, ArrayList<Hospitalization> hospitalizations) {
        this(resolveApplicationContext(), user, patient);
    }

    private static ApplicationContext resolveApplicationContext() {
        ApplicationContext context = Main.getApplicationContext();
        if (context == null) {
            context = new ApplicationContext();
            context.initialize();
        }
        return context;
    }

    @SuppressWarnings("unchecked")
    private void loadLegacyCollectionsFromContext() {
        this.users = (ArrayList<User>) applicationContext.getDataStore().getUsers();
        this.appointments = (ArrayList<Appointment>) applicationContext.getDataStore().getAppointments();
        this.hospitalizations = (ArrayList<Hospitalization>) applicationContext.getDataStore().getHospitalizations();
    }

    private void initializePatientView() {
        btnBackToAdminFromPatient.setVisible(user instanceof Administrator);
        loadPatientInformation();
        loadDoctorComboBoxForHospitalization();
        loadRoomTypes();
        loadCancelableAppointments();
        refreshAppointmentsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPatientWindow = new packagee.PanelRound();
        pnlPatientHeader = new packagee.PanelRound();
        btnClosePatient = new javax.swing.JButton();
        lblPatientViewTitle = new javax.swing.JLabel();
        btnBackToAdminFromPatient = new javax.swing.JButton();
        tabPatientSections = new javax.swing.JTabbedPane();
        pnlPatientAppointmentsVisualization = new javax.swing.JPanel();
        scrPatientAppointments = new javax.swing.JScrollPane();
        tblPatientAppointments = new javax.swing.JTable();
        btnRefreshPatientAppointments = new javax.swing.JButton();
        btnLogoutPatient = new javax.swing.JButton();
        pnlPatientInformation = new javax.swing.JPanel();
        lblPatientFirstName = new javax.swing.JLabel();
        txtPatientFirstName = new javax.swing.JTextField();
        lblPatientLastName = new javax.swing.JLabel();
        txtPatientLastName = new javax.swing.JTextField();
        lblPatientBirthdate = new javax.swing.JLabel();
        txtPatientBirthdate = new javax.swing.JTextField();
        lblPatientGender = new javax.swing.JLabel();
        lblPatientEmail = new javax.swing.JLabel();
        txtPatientEmail = new javax.swing.JTextField();
        lblPatientPhone = new javax.swing.JLabel();
        txtPatientPhone = new javax.swing.JTextField();
        lblPatientAddress = new javax.swing.JLabel();
        txtPatientAddress = new javax.swing.JTextField();
        txtPatientPassword = new javax.swing.JTextField();
        lblPatientPassword = new javax.swing.JLabel();
        lblPatientConfirmPassword = new javax.swing.JLabel();
        txtPatientConfirmPassword = new javax.swing.JTextField();
        btnUpdatePatientInfo = new javax.swing.JButton();
        lblPatientUsername = new javax.swing.JLabel();
        txtPatientUsername = new javax.swing.JTextField();
        cmbPatientGender = new javax.swing.JComboBox<>();
        pnlPatientRequests = new javax.swing.JPanel();
        lblRequestAppointmentTitle = new javax.swing.JLabel();
        rbtnRequestAppointmentBySpecialty = new javax.swing.JRadioButton();
        rbtnRequestAppointmentByDoctor = new javax.swing.JRadioButton();
        sepAppointmentRequest = new javax.swing.JSeparator();
        lblAppointmentDate = new javax.swing.JLabel();
        txtAppointmentDate = new javax.swing.JTextField();
        txtAppointmentTime = new javax.swing.JTextField();
        lblAppointmentTime = new javax.swing.JLabel();
        lblAppointmentType = new javax.swing.JLabel();
        lblAppointmentReason = new javax.swing.JLabel();
        cmbAppointmentType = new javax.swing.JComboBox<>();
        btnCreateAppointment = new javax.swing.JButton();
        sepHospitalizationRequest = new javax.swing.JSeparator();
        lblRequestHospitalizationTitle = new javax.swing.JLabel();
        lblHospitalizationReason = new javax.swing.JLabel();
        lblHospitalizationDoctor = new javax.swing.JLabel();
        cmbHospitalizationDoctor = new javax.swing.JComboBox<>();
        txtHospitalizationAdmissionDate = new javax.swing.JTextField();
        lblHospitalizationAdmissionDate = new javax.swing.JLabel();
        lblHospitalizationRoomType = new javax.swing.JLabel();
        cmbHospitalizationRoomType = new javax.swing.JComboBox<>();
        lblHospitalizationObservations = new javax.swing.JLabel();
        scrHospitalizationObservations = new javax.swing.JScrollPane();
        txaHospitalizationObservations = new javax.swing.JTextArea();
        btnCreateHospitalization = new javax.swing.JButton();
        lblCancelAppointmentTitle = new javax.swing.JLabel();
        lblCancelAppointmentId = new javax.swing.JLabel();
        lblCancelAppointmentObservations = new javax.swing.JLabel();
        scrCancelAppointmentObservations = new javax.swing.JScrollPane();
        txaCancelAppointmentObservations = new javax.swing.JTextArea();
        btnCancelAppointment = new javax.swing.JButton();
        scrHospitalizationReason = new javax.swing.JScrollPane();
        txaHospitalizationReason = new javax.swing.JTextArea();
        scrAppointmentReason = new javax.swing.JScrollPane();
        txaAppointmentReason = new javax.swing.JTextArea();
        cmbCancelableAppointments = new javax.swing.JComboBox<>();
        cmbAppointmentDoctorOrSpecialty = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlPatientWindow.setRadius(50);

        pnlPatientHeader.setRadius(50);
        pnlPatientHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        pnlPatientHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        btnClosePatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnClosePatient.setText("X");
        btnClosePatient.setBorderPainted(false);
        btnClosePatient.setContentAreaFilled(false);
        btnClosePatient.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClosePatient.setFocusable(false);
        btnClosePatient.setRequestFocusEnabled(false);
        btnClosePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClosePatientActionPerformed(evt);
            }
        });

        lblPatientViewTitle.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblPatientViewTitle.setText("PATIENT VIEW");

        btnBackToAdminFromPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnBackToAdminFromPatient.setText("Back");
        btnBackToAdminFromPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToAdminFromPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPatientHeaderLayout = new javax.swing.GroupLayout(pnlPatientHeader);
        pnlPatientHeader.setLayout(pnlPatientHeaderLayout);
        pnlPatientHeaderLayout.setHorizontalGroup(
            pnlPatientHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPatientHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPatientViewTitle)
                .addGap(29, 29, 29)
                .addComponent(btnBackToAdminFromPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClosePatient)
                .addGap(19, 19, 19))
        );
        pnlPatientHeaderLayout.setVerticalGroup(
            pnlPatientHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPatientHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClosePatient))
            .addGroup(pnlPatientHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackToAdminFromPatient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblPatientViewTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tblPatientAppointments.setAutoCreateRowSorter(true);
        tblPatientAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrPatientAppointments.setViewportView(tblPatientAppointments);

        btnRefreshPatientAppointments.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRefreshPatientAppointments.setText("Refresh");
        btnRefreshPatientAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshPatientAppointmentsActionPerformed(evt);
            }
        });

        btnLogoutPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogoutPatient.setText("Logout");
        btnLogoutPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPatientAppointmentsVisualizationLayout = new javax.swing.GroupLayout(pnlPatientAppointmentsVisualization);
        pnlPatientAppointmentsVisualization.setLayout(pnlPatientAppointmentsVisualizationLayout);
        pnlPatientAppointmentsVisualizationLayout.setHorizontalGroup(
            pnlPatientAppointmentsVisualizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientAppointmentsVisualizationLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(scrPatientAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(pnlPatientAppointmentsVisualizationLayout.createSequentialGroup()
                .addGap(602, 602, 602)
                .addComponent(btnRefreshPatientAppointments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogoutPatient)
                .addGap(78, 78, 78))
        );
        pnlPatientAppointmentsVisualizationLayout.setVerticalGroup(
            pnlPatientAppointmentsVisualizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientAppointmentsVisualizationLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(scrPatientAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(pnlPatientAppointmentsVisualizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshPatientAppointments)
                    .addComponent(btnLogoutPatient))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        tabPatientSections.addTab("Appointment history", pnlPatientAppointmentsVisualization);

        lblPatientFirstName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientFirstName.setText("Firstname");

        txtPatientFirstName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientLastName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientLastName.setText("Lastname");

        txtPatientLastName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientBirthdate.setText("Birthdate");

        txtPatientBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientGender.setText("Gender");

        lblPatientEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientEmail.setText("Email");

        txtPatientEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientPhone.setText("Phone");

        txtPatientPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientAddress.setText("Address");

        txtPatientAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPatientPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientPassword.setText("Password");

        lblPatientConfirmPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientConfirmPassword.setText("Password confirmation");

        txtPatientConfirmPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        btnUpdatePatientInfo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnUpdatePatientInfo.setText("Save");
        btnUpdatePatientInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePatientInfoActionPerformed(evt);
            }
        });

        lblPatientUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientUsername.setText("User");

        txtPatientUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        cmbPatientGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbPatientGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        javax.swing.GroupLayout pnlPatientInformationLayout = new javax.swing.GroupLayout(pnlPatientInformation);
        pnlPatientInformation.setLayout(pnlPatientInformationLayout);
        pnlPatientInformationLayout.setHorizontalGroup(
            pnlPatientInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientInformationLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblPatientFirstName)
                .addGap(18, 18, 18)
                .addComponent(txtPatientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblPatientLastName)
                .addGap(18, 18, 18)
                .addGroup(pnlPatientInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPatientInformationLayout.createSequentialGroup()
                        .addComponent(lblPatientPhone)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPatientAddress)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlPatientInformationLayout.createSequentialGroup()
                        .addComponent(txtPatientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPatientBirthdate)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPatientGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPatientGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblPatientEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
            .addGroup(pnlPatientInformationLayout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addGroup(pnlPatientInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPatientInformationLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnUpdatePatientInfo))
                    .addGroup(pnlPatientInformationLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(txtPatientConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPatientConfirmPassword)
                    .addGroup(pnlPatientInformationLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblPatientPassword))
                    .addGroup(pnlPatientInformationLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(pnlPatientInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlPatientInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPatientUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlPatientInformationLayout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(lblPatientUsername)))
                            .addComponent(txtPatientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPatientInformationLayout.setVerticalGroup(
            pnlPatientInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientInformationLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(pnlPatientInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientFirstName)
                    .addComponent(txtPatientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientLastName)
                    .addComponent(txtPatientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientBirthdate)
                    .addComponent(txtPatientBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientGender)
                    .addComponent(lblPatientEmail)
                    .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPatientGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPatientInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientPhone)
                    .addComponent(txtPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientAddress)
                    .addComponent(txtPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(lblPatientUsername)
                .addGap(18, 18, 18)
                .addComponent(txtPatientUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPatientPassword)
                .addGap(18, 18, 18)
                .addComponent(txtPatientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPatientConfirmPassword)
                .addGap(18, 18, 18)
                .addComponent(txtPatientConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnUpdatePatientInfo)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        tabPatientSections.addTab("Modify info", pnlPatientInformation);

        lblRequestAppointmentTitle.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRequestAppointmentTitle.setText("Request medical appointment");

        rbtnRequestAppointmentBySpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rbtnRequestAppointmentBySpecialty.setText("Specialty");
        rbtnRequestAppointmentBySpecialty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRequestAppointmentBySpecialtyActionPerformed(evt);
            }
        });

        rbtnRequestAppointmentByDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rbtnRequestAppointmentByDoctor.setText("Doctor");
        rbtnRequestAppointmentByDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRequestAppointmentByDoctorActionPerformed(evt);
            }
        });

        sepAppointmentRequest.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblAppointmentDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentDate.setText("Appointment date");

        txtAppointmentDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtAppointmentTime.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblAppointmentTime.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentTime.setText("Appointment time");

        lblAppointmentType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentType.setText("Appointment type");

        lblAppointmentReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentReason.setText("Appointment reason");

        cmbAppointmentType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbAppointmentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Remote", "In-person" }));

        btnCreateAppointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCreateAppointment.setText("Create");
        btnCreateAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAppointmentActionPerformed(evt);
            }
        });

        sepHospitalizationRequest.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblRequestHospitalizationTitle.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRequestHospitalizationTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequestHospitalizationTitle.setText("Request hospitalization");

        lblHospitalizationReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationReason.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalizationReason.setText("Hospitalization reason");

        lblHospitalizationDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalizationDoctor.setText("Attending doctor");

        cmbHospitalizationDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbHospitalizationDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        txtHospitalizationAdmissionDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblHospitalizationAdmissionDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationAdmissionDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalizationAdmissionDate.setText("Estimated date of admission");
        lblHospitalizationAdmissionDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblHospitalizationRoomType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationRoomType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalizationRoomType.setText("Desired room type");

        cmbHospitalizationRoomType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbHospitalizationRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        lblHospitalizationObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationObservations.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalizationObservations.setText("Observations");

        txaHospitalizationObservations.setColumns(20);
        txaHospitalizationObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txaHospitalizationObservations.setRows(5);
        scrHospitalizationObservations.setViewportView(txaHospitalizationObservations);

        btnCreateHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCreateHospitalization.setText("Create");
        btnCreateHospitalization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHospitalizationActionPerformed(evt);
            }
        });

        lblCancelAppointmentTitle.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblCancelAppointmentTitle.setText("Cancel appointment");

        lblCancelAppointmentId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblCancelAppointmentId.setText("ID appointment");

        lblCancelAppointmentObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblCancelAppointmentObservations.setText("Observations");

        txaCancelAppointmentObservations.setColumns(20);
        txaCancelAppointmentObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txaCancelAppointmentObservations.setRows(5);
        scrCancelAppointmentObservations.setViewportView(txaCancelAppointmentObservations);

        btnCancelAppointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCancelAppointment.setText("Cancel");
        btnCancelAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAppointmentActionPerformed(evt);
            }
        });

        txaHospitalizationReason.setColumns(20);
        txaHospitalizationReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txaHospitalizationReason.setRows(5);
        scrHospitalizationReason.setViewportView(txaHospitalizationReason);

        txaAppointmentReason.setColumns(20);
        txaAppointmentReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txaAppointmentReason.setRows(5);
        scrAppointmentReason.setViewportView(txaAppointmentReason);

        cmbCancelableAppointments.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbCancelableAppointments.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        cmbAppointmentDoctorOrSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbAppointmentDoctorOrSpecialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout pnlPatientRequestsLayout = new javax.swing.GroupLayout(pnlPatientRequests);
        pnlPatientRequests.setLayout(pnlPatientRequestsLayout);
        pnlPatientRequestsLayout.setHorizontalGroup(
            pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                .addGroup(pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                                    .addComponent(rbtnRequestAppointmentBySpecialty)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbtnRequestAppointmentByDoctor))
                                .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addGroup(pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblAppointmentTime)
                                        .addComponent(lblAppointmentDate)
                                        .addComponent(cmbAppointmentDoctorOrSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(txtAppointmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(lblAppointmentReason))
                                .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(lblAppointmentType))
                                .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(cmbAppointmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(lblRequestAppointmentTitle)))
                    .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(scrAppointmentReason, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnCreateAppointment)))
                .addGap(69, 69, 69)
                .addComponent(sepAppointmentRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addComponent(btnCreateHospitalization))
                        .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblHospitalizationReason, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scrHospitalizationReason, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(lblRequestHospitalizationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(lblHospitalizationDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPatientRequestsLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblHospitalizationObservations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHospitalizationAdmissionDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(scrHospitalizationObservations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHospitalizationRoomType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(cmbHospitalizationDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(txtHospitalizationAdmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(cmbHospitalizationRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(sepHospitalizationRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrCancelAppointmentObservations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                        .addGroup(pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblCancelAppointmentTitle))
                            .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btnCancelAppointment))
                            .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbCancelableAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCancelAppointmentId)))
                            .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lblCancelAppointmentObservations)))
                        .addGap(49, 49, 49)))
                .addGap(81, 81, 81))
        );
        pnlPatientRequestsLayout.setVerticalGroup(
            pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sepAppointmentRequest)
            .addComponent(sepHospitalizationRequest)
            .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                        .addComponent(lblRequestHospitalizationTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(lblHospitalizationReason)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrHospitalizationReason, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHospitalizationDoctor)
                        .addGap(18, 18, 18)
                        .addComponent(cmbHospitalizationDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHospitalizationAdmissionDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHospitalizationAdmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lblHospitalizationRoomType)
                        .addGap(18, 18, 18)
                        .addComponent(cmbHospitalizationRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHospitalizationObservations)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrHospitalizationObservations, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateHospitalization)
                        .addGap(15, 15, 15))
                    .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                        .addGroup(pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                                .addComponent(lblRequestAppointmentTitle)
                                .addGap(18, 18, 18)
                                .addGroup(pnlPatientRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtnRequestAppointmentBySpecialty)
                                    .addComponent(rbtnRequestAppointmentByDoctor))
                                .addGap(18, 18, 18)
                                .addComponent(cmbAppointmentDoctorOrSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAppointmentDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(lblAppointmentTime)
                                .addGap(18, 18, 18)
                                .addComponent(txtAppointmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAppointmentReason)
                                .addGap(24, 24, 24)
                                .addComponent(scrAppointmentReason, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPatientRequestsLayout.createSequentialGroup()
                                .addComponent(lblCancelAppointmentTitle)
                                .addGap(39, 39, 39)
                                .addComponent(lblCancelAppointmentId)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCancelableAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCancelAppointmentObservations)
                                .addGap(18, 18, 18)
                                .addComponent(scrCancelAppointmentObservations, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnCancelAppointment)))
                        .addGap(18, 18, 18)
                        .addComponent(lblAppointmentType)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAppointmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnCreateAppointment)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabPatientSections.addTab("Request/Cancel", pnlPatientRequests);

        javax.swing.GroupLayout pnlPatientWindowLayout = new javax.swing.GroupLayout(pnlPatientWindow);
        pnlPatientWindow.setLayout(pnlPatientWindowLayout);
        pnlPatientWindowLayout.setHorizontalGroup(
            pnlPatientWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPatientHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPatientSections)
        );
        pnlPatientWindowLayout.setVerticalGroup(
            pnlPatientWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientWindowLayout.createSequentialGroup()
                .addComponent(pnlPatientHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPatientSections))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPatientWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPatientWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void btnClosePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClosePatientActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnClosePatientActionPerformed

    private void btnCancelAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAppointmentActionPerformed
        String idAppointment = selectedComboValue(cmbCancelableAppointments);
        if (idAppointment.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita valida para cancelar.");
            return;
        }
        Response<?> response = appointmentController.cancelAppointment(idAppointment);
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isSuccess()) {
            loadCancelableAppointments();
            refreshAppointmentsTable();
        }
    }//GEN-LAST:event_btnCancelAppointmentActionPerformed

    private void btnUpdatePatientInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePatientInfoActionPerformed
        PatientRequest request = new PatientRequest(
                String.valueOf(patient.getId()),
                txtPatientUsername.getText().trim(),
                txtPatientFirstName.getText().trim(),
                txtPatientLastName.getText().trim(),
                txtPatientPassword.getText(),
                txtPatientConfirmPassword.getText(),
                txtPatientEmail.getText().trim(),
                txtPatientBirthdate.getText().trim(),
                selectedComboValue(cmbPatientGender),
                txtPatientPhone.getText().trim(),
                txtPatientAddress.getText().trim()
        );
        Response<?> response = patientController.updatePatient(request);
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isSuccess()) {
            patient = applicationContext.getUserRepository().findPatientById(patient.getId()).orElse(patient);
            txtPatientPassword.setText("");
            txtPatientConfirmPassword.setText("");
            loadPatientInformation();
        }

    }//GEN-LAST:event_btnUpdatePatientInfoActionPerformed

    private void btnLogoutPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutPatientActionPerformed
        authController.logout();
        LoginView login = new LoginView(applicationContext);
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutPatientActionPerformed

    private void btnBackToAdminFromPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToAdminFromPatientActionPerformed
        AdminView admin = new AdminView(applicationContext, user);
        this.setVisible(false);
        admin.setVisible(true);
    }//GEN-LAST:event_btnBackToAdminFromPatientActionPerformed

    private void rbtnRequestAppointmentBySpecialtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRequestAppointmentBySpecialtyActionPerformed
        if (rbtnRequestAppointmentByDoctor.isSelected()) {
            rbtnRequestAppointmentByDoctor.setSelected(false);
        }
        loadSpecialtyComboBoxForAppointment();
    }//GEN-LAST:event_rbtnRequestAppointmentBySpecialtyActionPerformed

    private void rbtnRequestAppointmentByDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRequestAppointmentByDoctorActionPerformed
        if (rbtnRequestAppointmentBySpecialty.isSelected()) {
            rbtnRequestAppointmentBySpecialty.setSelected(false);
        }
        loadDoctorComboBoxForAppointment();
    }//GEN-LAST:event_rbtnRequestAppointmentByDoctorActionPerformed

    private void btnCreateAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAppointmentActionPerformed
        String doctorId = "";
        String specialty = "";

        if (rbtnRequestAppointmentByDoctor.isSelected()) {
            doctorId = selectedComboValue(cmbAppointmentDoctorOrSpecialty);
            if (doctorId.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Seleccione un doctor valido.");
                return;
            }
            Doctor doctor = applicationContext.getUserRepository()
                    .findDoctorById(Long.parseLong(doctorId))
                    .orElse(null);
            if (doctor == null) {
                JOptionPane.showMessageDialog(this, "No fue posible obtener la especialidad del doctor.");
                return;
            }
            specialty = doctor.getSpecialty().name();
        } else if (rbtnRequestAppointmentBySpecialty.isSelected()) {
            specialty = normalizeSpecialty(selectedComboValue(cmbAppointmentDoctorOrSpecialty));
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione si la cita se solicita por especialidad o por doctor.");
            return;
        }

        AppointmentRequest request = new AppointmentRequest(
                String.valueOf(patient.getId()),
                doctorId,
                specialty,
                txtAppointmentDate.getText().trim(),
                txtAppointmentTime.getText().trim(),
                txaAppointmentReason.getText().trim(),
                selectedComboValue(cmbAppointmentType)
        );

        Response<?> response = appointmentController.requestAppointment(request);
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isSuccess()) {
            clearAppointmentRequestFields();
            loadCancelableAppointments();
            refreshAppointmentsTable();
        }
    }//GEN-LAST:event_btnCreateAppointmentActionPerformed


    private void btnRefreshPatientAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshPatientAppointmentsActionPerformed
        refreshAppointmentsTable();
        loadCancelableAppointments();
    }//GEN-LAST:event_btnRefreshPatientAppointmentsActionPerformed

    private void btnCreateHospitalizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHospitalizationActionPerformed
        HospitalizationRequest request = new HospitalizationRequest(
                String.valueOf(patient.getId()),
                selectedComboValue(cmbHospitalizationDoctor),
                txtHospitalizationAdmissionDate.getText().trim(),
                txaHospitalizationReason.getText().trim(),
                selectedComboValue(cmbHospitalizationRoomType),
                txaHospitalizationObservations.getText().trim()
        );
        Response<?> response = hospitalizationController.requestHospitalization(request);
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isSuccess()) {
            clearHospitalizationRequestFields();
        }
    }//GEN-LAST:event_btnCreateHospitalizationActionPerformed



    private void loadPatientInformation() {
        if (patient == null) {
            return;
        }
        txtPatientFirstName.setText(patient.getFirstname());
        txtPatientLastName.setText(patient.getLastname());
        txtPatientBirthdate.setText(patient.getBirthdate() == null ? "" : patient.getBirthdate().toString());
        txtPatientEmail.setText(patient.getEmail());
        txtPatientPhone.setText(String.valueOf(patient.getPhone()));
        txtPatientAddress.setText(patient.getAddress());
        txtPatientUsername.setText(patient.getUsername());
        txtPatientPassword.setText("");
        txtPatientConfirmPassword.setText("");
        cmbPatientGender.setSelectedIndex(patient.isGender() ? 2 : 1);
    }

    private void loadDoctorComboBoxForAppointment() {
        cmbAppointmentDoctorOrSpecialty.removeAllItems();
        cmbAppointmentDoctorOrSpecialty.addItem("Select one");
        Response<java.util.List<DoctorDTO>> response = doctorController.getAllDoctors();
        if (response.isSuccess()) {
            for (DoctorDTO doctor : response.getData()) {
                cmbAppointmentDoctorOrSpecialty.addItem(String.valueOf(doctor.getId()));
            }
        }
    }

    private void loadSpecialtyComboBoxForAppointment() {
        cmbAppointmentDoctorOrSpecialty.removeAllItems();
        cmbAppointmentDoctorOrSpecialty.addItem("Select one");
        for (Specialty specialty : Specialty.values()) {
            cmbAppointmentDoctorOrSpecialty.addItem(toDisplayText(specialty.name()));
        }
    }

    private void loadDoctorComboBoxForHospitalization() {
        cmbHospitalizationDoctor.removeAllItems();
        cmbHospitalizationDoctor.addItem("Select one");
        Response<java.util.List<DoctorDTO>> response = doctorController.getAllDoctors();
        if (response.isSuccess()) {
            for (DoctorDTO doctor : response.getData()) {
                cmbHospitalizationDoctor.addItem(String.valueOf(doctor.getId()));
            }
        }
    }

    private void loadRoomTypes() {
        cmbHospitalizationRoomType.removeAllItems();
        cmbHospitalizationRoomType.addItem("Select one");
        for (RoomType roomType : RoomType.values()) {
            cmbHospitalizationRoomType.addItem(roomType.name());
        }
    }

    private void loadCancelableAppointments() {
        cmbCancelableAppointments.removeAllItems();
        cmbCancelableAppointments.addItem("Select one");
        Response<java.util.List<AppointmentDTO>> response = appointmentController.getPatientAppointments(patient.getId());
        if (response.isSuccess()) {
            for (AppointmentDTO appointment : response.getData()) {
                if (!"COMPLETED".equalsIgnoreCase(appointment.getStatus())
                        && !"CANCELED".equalsIgnoreCase(appointment.getStatus())) {
                    cmbCancelableAppointments.addItem(appointment.getId());
                }
            }
        }
    }

    private void refreshAppointmentsTable() {
        DefaultTableModel model = (DefaultTableModel) tblPatientAppointments.getModel();
        model.setRowCount(0);
        Response<java.util.List<AppointmentDTO>> response = appointmentController.getPatientAppointments(patient.getId());
        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(this, response.getMessage());
            return;
        }
        for (AppointmentDTO appointment : response.getData()) {
            model.addRow(new Object[]{
                    appointment.getId(),
                    appointment.getDate() + " " + appointment.getTime(),
                    appointment.getDoctorName(),
                    appointment.getSpecialty(),
                    appointment.getType(),
                    appointment.getStatus()
            });
        }
    }

    private String selectedComboValue(javax.swing.JComboBox<String> comboBox) {
        Object selected = comboBox.getSelectedItem();
        if (selected == null || "Select one".equalsIgnoreCase(selected.toString())) {
            return "";
        }
        return selected.toString();
    }


    @Override
    public void onModelChanged(ModelEvent event) {
        if (event == null || applicationContext == null || patient == null) {
            return;
        }
        SwingUtilities.invokeLater(() -> {
            if (event.getType() == ModelEventType.USERS_CHANGED || event.getType() == ModelEventType.ALL_CHANGED) {
                loadDoctorComboBoxForAppointment();
                loadDoctorComboBoxForHospitalization();
                loadSpecialtyComboBoxForAppointment();
            }
            if (event.getType() == ModelEventType.APPOINTMENTS_CHANGED || event.getType() == ModelEventType.ALL_CHANGED) {
                loadCancelableAppointments();
                refreshAppointmentsTable();
            }
            if (event.getType() == ModelEventType.HOSPITALIZATIONS_CHANGED || event.getType() == ModelEventType.ALL_CHANGED) {
                loadDoctorComboBoxForHospitalization();
                loadRoomTypes();
            }
        });
    }

    @Override
    public void dispose() {
        if (applicationContext != null) {
            applicationContext.getModelEventPublisher().removeObserver(this);
        }
        super.dispose();
    }

    private String normalizeSpecialty(String value) {
        if (value == null || value.trim().isEmpty()) {
            return "";
        }
        return value.trim().toUpperCase().replace(" & ", "_").replace(" ", "_");
    }

    private String toDisplayText(String enumName) {
        String lower = enumName.toLowerCase().replace('_', ' ');
        StringBuilder builder = new StringBuilder();
        for (String word : lower.split(" ")) {
            if (!word.trim().isEmpty()) {
                builder.append(Character.toUpperCase(word.charAt(0)))
                        .append(word.substring(1))
                        .append(" ");
            }
        }
        return builder.toString().trim();
    }

    private void clearAppointmentRequestFields() {
        txtAppointmentDate.setText("");
        txtAppointmentTime.setText("");
        txaAppointmentReason.setText("");
        cmbAppointmentType.setSelectedIndex(0);
        cmbAppointmentDoctorOrSpecialty.removeAllItems();
        cmbAppointmentDoctorOrSpecialty.addItem("Select one");
        rbtnRequestAppointmentBySpecialty.setSelected(false);
        rbtnRequestAppointmentByDoctor.setSelected(false);
    }

    private void clearHospitalizationRequestFields() {
        txaHospitalizationReason.setText("");
        txtHospitalizationAdmissionDate.setText("");
        txaHospitalizationObservations.setText("");
        cmbHospitalizationDoctor.setSelectedIndex(0);
        cmbHospitalizationRoomType.setSelectedIndex(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToAdminFromPatient;
    private javax.swing.JButton btnCancelAppointment;
    private javax.swing.JButton btnClosePatient;
    private javax.swing.JButton btnCreateAppointment;
    private javax.swing.JButton btnCreateHospitalization;
    private javax.swing.JButton btnLogoutPatient;
    private javax.swing.JButton btnRefreshPatientAppointments;
    private javax.swing.JButton btnUpdatePatientInfo;
    private javax.swing.JComboBox<String> cmbAppointmentType;
    private javax.swing.JComboBox<String> cmbHospitalizationDoctor;
    private javax.swing.JComboBox<String> cmbHospitalizationRoomType;
    private javax.swing.JComboBox<String> cmbCancelableAppointments;
    private javax.swing.JComboBox<String> cmbAppointmentDoctorOrSpecialty;
    private javax.swing.JComboBox<String> cmbPatientGender;
    private javax.swing.JLabel lblPatientViewTitle;
    private javax.swing.JLabel lblPatientPassword;
    private javax.swing.JLabel lblPatientConfirmPassword;
    private javax.swing.JLabel lblPatientUsername;
    private javax.swing.JLabel lblRequestAppointmentTitle;
    private javax.swing.JLabel lblAppointmentDate;
    private javax.swing.JLabel lblAppointmentTime;
    private javax.swing.JLabel lblAppointmentType;
    private javax.swing.JLabel lblAppointmentReason;
    private javax.swing.JLabel lblRequestHospitalizationTitle;
    private javax.swing.JLabel lblHospitalizationReason;
    private javax.swing.JLabel lblPatientFirstName;
    private javax.swing.JLabel lblHospitalizationDoctor;
    private javax.swing.JLabel lblHospitalizationAdmissionDate;
    private javax.swing.JLabel lblHospitalizationRoomType;
    private javax.swing.JLabel lblHospitalizationObservations;
    private javax.swing.JLabel lblCancelAppointmentTitle;
    private javax.swing.JLabel lblCancelAppointmentId;
    private javax.swing.JLabel lblCancelAppointmentObservations;
    private javax.swing.JLabel lblPatientLastName;
    private javax.swing.JLabel lblPatientBirthdate;
    private javax.swing.JLabel lblPatientGender;
    private javax.swing.JLabel lblPatientEmail;
    private javax.swing.JLabel lblPatientPhone;
    private javax.swing.JLabel lblPatientAddress;
    private javax.swing.JPanel pnlPatientInformation;
    private javax.swing.JPanel pnlPatientRequests;
    private javax.swing.JPanel pnlPatientAppointmentsVisualization;
    private javax.swing.JRadioButton rbtnRequestAppointmentBySpecialty;
    private javax.swing.JRadioButton rbtnRequestAppointmentByDoctor;
    private javax.swing.JScrollPane scrHospitalizationObservations;
    private javax.swing.JScrollPane scrCancelAppointmentObservations;
    private javax.swing.JScrollPane scrPatientAppointments;
    private javax.swing.JScrollPane scrHospitalizationReason;
    private javax.swing.JScrollPane scrAppointmentReason;
    private javax.swing.JSeparator sepAppointmentRequest;
    private javax.swing.JSeparator sepHospitalizationRequest;
    private javax.swing.JTabbedPane tabPatientSections;
    private javax.swing.JTable tblPatientAppointments;
    private javax.swing.JTextArea txaHospitalizationObservations;
    private javax.swing.JTextArea txaCancelAppointmentObservations;
    private javax.swing.JTextArea txaHospitalizationReason;
    private javax.swing.JTextArea txaAppointmentReason;
    private javax.swing.JTextField txtPatientFirstName;
    private javax.swing.JTextField txtPatientConfirmPassword;
    private javax.swing.JTextField txtPatientUsername;
    private javax.swing.JTextField txtAppointmentDate;
    private javax.swing.JTextField txtAppointmentTime;
    private javax.swing.JTextField txtHospitalizationAdmissionDate;
    private javax.swing.JTextField txtPatientLastName;
    private javax.swing.JTextField txtPatientBirthdate;
    private javax.swing.JTextField txtPatientEmail;
    private javax.swing.JTextField txtPatientPhone;
    private javax.swing.JTextField txtPatientAddress;
    private javax.swing.JTextField txtPatientPassword;
    private packagee.PanelRound pnlPatientWindow;
    private packagee.PanelRound pnlPatientHeader;
    // End of variables declaration//GEN-END:variables
}
